# Generated by Django 5.0.7 on 2024-07-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_course_program_userregister_remove_message_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
