# Generated by Django 5.0.7 on 2024-07-21 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_alter_userregister_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegister',
        ),
    ]
